version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: practice4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - '${POSTGRES_PORT:-5430}:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-mydatabase}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - app_data:/var/lib/postgresql/data

volumes:
  app_data:
